export const mockData = [
  {
    description: 'Compact city car, great for tight parking.',
    make: 'Honda',
    year: 2022,
    color: 'Blue',
    price: '$20,000',
    picture: 'https://unsplash.com/photos/example1',
  },
  {
    description: 'Luxury sedan with top-tier amenities.',
    make: 'Mercedes',
    year: 2021,
    color: 'Black',
    price: '$40,000',
    picture: 'https://unsplash.com/photos/example2',
  },
  {
    description: 'Economical family sedan with ample space.',
    make: 'Toyota',
    year: 2020,
    color: 'Silver',
    price: '$25,000',
    picture: 'https://unsplash.com/photos/example3',
  },
  {
    description: 'Sporty coupe with impressive performance.',
    make: 'Ford',
    year: 2019,
    color: 'Red',
    price: '$30,000',
    picture: 'https://unsplash.com/photos/example4',
  },
  {
    description: 'Versatile SUV perfect for off-road and city life.',
    make: 'Jeep',
    year: 2022,
    color: 'Green',
    price: '$35,000',
    picture: 'https://unsplash.com/photos/example5',
  },
  {
    description: 'Reliable and efficient, ideal for daily commuting.',
    make: 'Hyundai',
    year: 2018,
    color: 'White',
    price: '$18,000',
    picture: 'https://unsplash.com/photos/example6',
  },
  {
    description: 'Family-friendly minivan with modern safety features.',
    make: 'Kia',
    year: 2022,
    color: 'Brown',
    price: '$28,000',
    picture: 'https://unsplash.com/photos/example7',
  },
  {
    description: 'Electric vehicle with zero emissions and quick charging.',
    make: 'Tesla',
    year: 2023,
    color: 'Midnight Silver',
    price: '$45,000',
    picture: 'https://unsplash.com/photos/example8',
  },
  {
    description: 'High-performance sports car with cutting-edge technology.',
    make: 'Porsche',
    year: 2021,
    color: 'Yellow',
    price: '$80,000',
    picture: 'https://unsplash.com/photos/example9',
  },
  {
    description: 'Rugged pickup truck capable of handling any terrain.',
    make: 'Chevrolet',
    year: 2020,
    color: 'Orange',
    price: '$50,000',
    picture: 'https://unsplash.com/photos/example10',
  },
  {
    description: 'Luxurious and powerful, designed for comfort and speed.',
    make: 'BMW',
    year: 2019,
    color: 'Blue',
    price: '$55,000',
    picture: 'https://unsplash.com/photos/example11',
  },
  {
    description: 'Entry-level compact car, ideal for first-time car buyers.',
    make: 'Nissan',
    year: 2021,
    color: 'Grey',
    price: '$19,000',
    picture: 'https://unsplash.com/photos/example12',
  },
];
